# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 05:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default=datetime.datetime(2016, 5, 20, 5, 4, 41, 215700, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
